name: Publish NuGet

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
     
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
          
      - name: Restore NuGet Packages
        run: nuget restore WCFDistributedTracing\WCFDistributedTracing.csproj
        
      - name: Build
        run: msbuild WCFDistributedTracing\WCFDistributedTracing.csproj /p:Configuration=Release
 
      - name: Pack
        run: nuget pack WCFDistributedTracing.csproj -Properties Configuration=Release
        working-directory: WCFDistributedTracing
        
      - run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -k ${{ secrets.NuGetAPIKey }}
        working-directory: WCFDistributedTracing
