name: Publish NuGet

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
     
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - uses: nuget/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: 'latest'
          
      - name: Restore NuGet Packages
        run: nuget restore WCFDistributedTracing\WCFDistributedTracing.csproj
        
      - name: Build
        run: msbuild WCFDistributedTracing\WCFDistributedTracing.csproj /p:Configuration=Release
 
      - name: Pack
        run: nuget pack WCFDistributedTracing.csproj -Properties Configuration=Release
        working-directory: WCFDistributedTracing
        
      - run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
        working-directory: WCFDistributedTracing
